### ISSUE TITLE
Join with the DotNetAnalyzers organisation

### ISSUE THREAD

**Issue by jimmyheaddon** [TheAlmightyBob/AsyncVoidAnalyzer#3]
Great extension, this will really help.  Just a suggestion, it might be worthwhile you joining with the [DotNetAnalyzers](https://github.com/DotNetAnalyzers) group so as to avoid duplicated effort.

**Comment by TheAlmightyBob** [comment]
Thanks for the tip, wasn't aware of that group.
However, I see that they already have an async void analyzer that takes a different approach...
